name: Test Project
on:
  pull_request:
    branches: [main]

  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: 20.11
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with: 
          path: node_modules
          key: deps-node-module-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependecies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with: 
          node-version: 20.11
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v4
        with: 
          path: node_modules
          key: deps-node-module-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependecies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Test code
        run: npm run test:prod
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/composite@v2
        if: always()
        with:
          files: |
            test/**/*.xml
